### ISSUE TITLE
Known issues for 1.0.0-beta

### ISSUE THREAD

**Issue by deviantony** [portainer/k2d#68]
This is a thread to reference known issues for the 1.0.0-beta release.

- [ ] Unable to list Secret and ConfigMap resources with k9s: https://github.com/portainer/k2d/issues/68#issuecomment-1744626548
- [x] An error is raised when creating a namespace with Lens/OpenLens: https://github.com/portainer/k2d/issues/68#issuecomment-1744630021
- [x] Creating workloads and resources inside a non existing namespace silently fails: https://github.com/portainer/k2d/issues/68#issuecomment-1748280100
- [x] Applying a manifest that creates a namespace and multiple resources within that namespace will fail with "namespace not found" error: https://github.com/portainer/k2d/issues/68#issuecomment-1754483554
- [x] Creating services when k2d runs under Podman fails: https://github.com/portainer/k2d/issues/68#issuecomment-1766141372

**Comment by deviantony** [comment]
Unable to list Secret and ConfigMap resources using k9s: https://github.com/derailed/k9s/issues/2238

The following errors are returned.

For secrets:
```
ERR Watcher failed for v1/secrets -- no kind "SecretList" is registered for version "v1" in scheme "pkg/runtime/scheme.go:100"
```

For configmaps:
```
ERR Watcher failed for v1/configmaps -- no kind "ConfigMapList" is registered for version "v1" in scheme "pkg/runtime/scheme.go:100"
```

**Comment by deviantony** [comment]
- [x] Fixed via https://github.com/portainer/k2d/pull/69

An error is raised when creating a namespace with Lens/OpenLens.

The following error is displayed:
![image](https://github.com/portainer/k2d/assets/5485061/6e7e49df-c0e4-4946-8a07-e7520164fd15)


However, refreshing the view shows that the namespace is actually created:
![image](https://github.com/portainer/k2d/assets/5485061/86a9d93d-40e7-4372-865c-0f42f37026d1)

**Comment by deviantony** [comment]
- [x] Fixed via https://github.com/portainer/k2d/pull/70

Creating workloads and resources inside a non existing namespace silently fails.

```
# kubectl outputs a success deployment
kubectl create deployment nginx --image=nginx:latest -n doesntexist
deployment.apps/nginx created
```

The following error is raised in k2d logs:
```
2023-10-05T07:39:58.300Z        ERROR   controller/controller.go:190    unable to create deployment     {"error": "Error response from daemon: network k2d-doesntexist not found"}
```

On a vanilla k8s, the following error is returned by `kubectl`:
```
kubectl create deployment nginx --image=nginx:latest -n doesntexist
error: failed to create deployment: namespaces "doesntexist" not found
```

**Comment by deviantony** [comment]
- [x] Fixed via https://github.com/portainer/k2d/pull/72

Applying a manifest that creates a namespace and multiple resources within that namespace will fail with "namespace not found" error:

Using the following nodered.yml manifest:

```yaml
apiVersion: v1
kind: Namespace
metadata:
  name: node-red
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: node-red
  namespace: node-red
  labels:
    app: node-red
spec:
  selector:
    matchLabels:
      app: node-red
  template:
    metadata:
      labels:
        app: node-red
    spec:
      containers:
      - name: node-red
        image: nodered/node-red:latest
        ports:
        - containerPort: 1880
        securityContext:
          privileged: true
        volumeMounts:
        - name: node-red-data
          mountPath: /data
        env:
        - name: NODE_NAME
          valueFrom:
            fieldRef:
              fieldPath: spec.nodeName
        - name: TZ
          value: America/Los_Angeles
      volumes:
      - name: node-red-data
        persistentVolumeClaim:
          claimName: node-red-claim
---
kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: node-red-claim
  namespace: node-red
spec:
  accessModes:
  - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
---
apiVersion: v1
kind: Service
metadata:
  name: node-red
  namespace: node-red
spec:
  selector:
    app: node-red
  type: LoadBalancer
  ports:
    - name: node-red-ui
      port: 1880
      protocol: TCP
      targetPort: 1880
```

Trying to apply this manifest:

```
kubectl apply -f nodered.yml
namespace/node-red created
Error from server (NotFound): error when creating "nodered.yml": namespaces "node-red" not found
Error from server (NotFound): error when creating "nodered.yml": namespaces "node-red" not found
Error from server (NotFound): error when creating "nodered.yml": namespaces "node-red" not found
```

Likely, the deletion of the manifest will fail as well:

```
kubectl delete -f nodered.yml
namespace/node-red created
Error from server (NotFound): error when creating "nodered.yml": namespaces "node-red" not found
Error from server (NotFound): error when creating "nodered.yml": namespaces "node-red" not found
Error from server (NotFound): error when creating "nodered.yml": namespaces "node-red" not found
```

This issue has been introduced following the fix for https://github.com/portainer/k2d/issues/68#issuecomment-1748280100 (via https://github.com/portainer/k2d/pull/70)

**Comment by deviantony** [comment]
- [x] After more testing, this seems to happen only on "unusual" Podman setups/configurations such as installing Podman on Ubuntu. The recommendation here is to use Podman on CentOS 8 which works without issue. We recommend this approach unless you know what you are doing when installing Podman on a non standard OS/configuration.

Applying a manifest that contains a service definition when running k2d under Podman fails to create the container with the following error:

```
ERROR	controller/controller.go:212	unable to update container	{"error": "unable to create container: Error response from daemon: fill out specgen: ulimit option \"RLIMIT_NOFILE=1048576:1048576\" requires name=SOFT:HARD, failed to be parsed: invalid ulimit type: RLIMIT_NOFILE", "request_id": "04b0d175-ce7b-4384-93dc-139f9d1fc132"}
```

**Comment by deviantony** [comment]
Closing in favor of https://github.com/portainer/k2d/issues/83
